permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: kramdown

# 作者信息
author: 
  name: Zheng Wei
  email: zhengwei@lanqiao.org
  link: http://lanqiao2016.github.io
  weibo: 
  github: http://github.com/lanqiao2016
  music: http://site.douban.com/linanya
  linkedin: 

# 站点信息
title: 蓝桥软件学院
description: My personal blog
url: http://lanqiao2016.github.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/蓝桥-图形@2x_24.png
favicon: /public/img/蓝桥-图形@2x_24.png

# google analytics 设置
ga:
  id: UA-54262064-1 
  url: lanqiao2016.github.io

# disqus 设置
disqus:
  shortname: lanqiao

# 主题设置，自动激活某个标签
active: basic

# 首页除了最新文章外显示分类
cates: 
#  - Optimization
#  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  roadmap: 路线
  basic: 基础
  advanced: 进阶
  project: 项目
  frontiers: 前沿
  interview: 面试
  
cates_basic:
    - Java8编程语言
    - JDBC入门教程
    - JDK核心API
    - HTML入门教程
    - jQuery基础教程
    - jQuery-easyui基础教程
    - H5入门教程
    - 数据库入门教程
    - JSP、Servlet编程
    - Spring框架教程
    - SpringMVC框架教程
    - MyBatis框架教程
    - 安卓入门教程
    - 常用工具使用教程
cates_advanced:
    - 数据结构与算法
    - 设计模式
    - clean code
    - guava解析
    - 缓存
    - apache-commons包解析
    - 数据库性能调优
    - 存储过程
    - JVM性能调优
    - 系统安全与Shiro框架教程
    - 框架源码解读系列
cates_project:
    - JavaSe实现五子棋游戏
    - JavaSe实现植物大战僵尸
    - JavaSe实现记事本
    - BootStrap+Jekyll搭建个人博客系统
    - H5游戏实战项目
    - Servlet实现综合类购物网站及后台管理系统
    - Servlet实现OA系统
    - SSM+Shiro实现基于角色的权限管理通用模块  
    - JavaEE全栈式项目化工程实践概述
    - SSM框架实现蓝桥教学教务管理系统

cates_frontiers:
    - 大数据
    - 物联网
    - 云计算
    - 人工智能

cates_interview:
    - JavaEE面试