permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: Zheng Wei
  email: zhengwei@lanqiao.org
  link: http://lanqiao.org
  weibo: 
  github: http://github.com/lanqiao2016
  music: http://site.douban.com/linanya
  linkedin: 

# 站点信息
title: 蓝桥软件学院
description: My personal blog
url: http://lanqiao.org
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/蓝桥-图形@2x_24.png
favicon: /public/img/蓝桥-图形@2x_24.png

# google analytics 设置
ga:
  id: UA-54262064-1 
  url: lanqiao.org

# disqus 设置
disqus:
  shortname: lanqiao

# 主题设置，自动激活某个标签
active: Java核心

# 首页除了最新文章外显示分类
cates: 
  - Optimization
  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档